$schema: ../../schema/mcp-agent.config.schema.json

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    everything-search:
      command: "uvx"
      args: ["mcp-server-everything-search"]
    desktop-commander:
      command: "npx"
      args: ["-y ", "@wonderwhy-er/desktop-commander"]
    mcp-server-commands:
      command: "npx"
      args: ["mcp-server-commands"]
    memory:
      command: "npx"
      args: [
        "-y", 
        "@modelcontextprotocol/server-memory"
      ]
    cli-mcp-server:
      command: "uvx"
      args: [
        'cli-mcp-server'
      ]
