$schema: ../../schema/mcp-agent.config.schema.json

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    everything-search:
      command: "uvx"
      args: ["mcp-server-everything-search"]
    mcp-server-commands:
      command: "npx"
      args: ["mcp-server-commands"]
    memory:
      command: "npx"
      args: [
        "-y", 
        "@modelcontextprotocol/server-memory"
      ]

openai:
  default_model: gpt-4o
